services:
  backend-spring:
    build: './spring-backend'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}'
      - 'DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}'
      - 'JWT_SECRET=${JWT_SECRET}'
      - 'SPRING_DATA_REDIS_HOST=${DEFAULT_REDIS_HOST}'
      - 'SPRING_DATA_REDIS_PORT=${DEFAULT_REDIS_PORT}'
      - 'SPRING_KAFKA_BOOTSTRAP_SERVERS=${DEFAULT_KAFKA}'
      - 'DEFAULT_RATELIMIT_REQUESTS=${DEFAULT_RATELIMIT_REQUESTS}'
      - 'DEFAULT_RATELIMIT_WINDOW=${DEFAULT_RATELIMIT_WINDOW}'
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  ktor-service:
    build: './ktor-service'
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "3000:3000"
#    deploy:
#      replicas: 2

  postgres:
    image: 'postgres:18'
    mem_limit: 512m
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mydatabase -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ktor-service

  admin-frontend:
    build: './admin-frontend'
    container_name: admin-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend-spring
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 7s
      retries: 3
      start_period: 10s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  pg_data:
  redis_data:
  kafka_data: