# ТОЛЬКО настройки для GitHub Actions
services:
  backend-spring:
    build:
      cache_from:
        - type=gha,scope=spring
      cache_to:
        - type=gha,mode=max,scope=spring
      environment:
        - JAVA_TOOL_OPTIONS=-Xmx512m

  ktor-service:
    build:
      cache_from:
        - type=gha,scope=ktor
      cache_to:
        - type=gha,mode=max,scope=ktor
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m

  admin-frontend:
    profiles:
      - donotstart

  notification-service:
    profiles:
      - donotstart

  dbgate:
    profiles:
      - donotstart
  kafka:
    environment:
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
