-- AVOID_TRANSACTION

ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'UPDATE_SETTINGS';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'ADD_MANAGED_IP';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'REMOVE_MANAGED_IP';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'SEED_DEFAULT_RULES';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'CREATE_ADMIN';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'DELETE_ADMIN';
ALTER TYPE AUDIT_ACTION ADD VALUE IF NOT EXISTS 'CHANGE_PASSWORD';