
ktor:
  application:
    modules:
      - com.pavelryzh.ApplicationKt.module
  deployment:
    port: 3000
  kafka:
    bootstrapServers: "kafka:29092"
    consumerGroupId: "ktor-gateway-group"
    producerClientId: "ktor-gateway-producer"

    producer:
      # Обязательно укажи сериализаторы для строк (ключ) и JSON (значение)
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer # Если шлешь JSON как обычную String

    topics:
      # Меняем дефолтное имя на то, которое вы заложили в архитектуре
      - name: traffic-logs
        partitions: 1
        configs:
          message.timestamp.type: CreateTime
