
ktor:
  application:
    modules:
      - com.pavelryzh.ApplicationKt.module
  deployment:
    port: 3000
  kafka:
    bootstrapServers: "kafka:29092"
    consumerGroupId: "ktor-gateway-group"
    producerClientId: "ktor-gateway-producer"

    producer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: org.apache.kafka.common.serialization.StringSerializer

    topics:
      - name: traffic-logs
        partitions: 1
        configs:
          message.timestamp.type: CreateTime
    redis:
      url: "redis://redis:6379"
